version: "3" 

services: 
  app: 
    container_name: nodejs
    build: .
    environment:
      - DB_HOST
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - DB_PORT
    env_file:
    - .env
    ports:
        - "3001:3001"
    restart: on-failure